// const gameSelected = [
//   {
//     'image': 'assets/images/movie.jpg',
//     'words': ['Escape Room', 'Titanic', 'Doraemon']
//   },
//   {
//     'image': 'assets/images/sport.jpg',
//     'words': ['Escape Room', 'Titanic', 'Doraemon']
//   },
//   {
//     'image': 'assets/images/food.jpg',
//     'words': ['Escape Room', 'Titanic', 'Doraemon']
//   },
// ];

const gameSelected = [
  {
    'image': 'assets/images/movie.jpg',
    'words': [
      'Escape Room',
      'Titanic',
      'Doraemon',
      'Interstellar',
      'Boyhood',
      'Whiplash',
      'Maleficent',
      'Nightcrawler',
      'Budapest Hotel',
      'The Lego Movie',
      'Gone Girl',
      'The Fault in Our Stars',
      'Big Hero 6',
      'The Kings Speech',
      'Harry Potter',
      'The Queen',
      'Lord of the Rings',
      'Chocolate Factory',
      'Beauty and the Beast',
      'The Sound of Music',
      'The Remains of the Day',
      'Skylines',
      'The marksman',
      'You Again',
      'Longshot',
      'Empire State',
      'Planet 51',
      'Faster',
      'Zootopia',
      'Baywatch'
    ]
  },
  {
    'image': 'assets/images/sport.jpg',
    'words': [
      'Badminton',
      'Baseball',
      'Basketball',
      'Bodybuilding',
      'Bowling',
      'Boxing',
      'Car Racing',
      'Cheerleading',
      'Chess',
      'Cricket',
      'Diving',
      'Dodgeball',
      'Figure Skating',
      'Football ',
      'Golf',
      'Handball',
      'Ice Skating',
      'Judo',
      'Karate',
      'Paintball',
      'Parachuting',
      'Rugby',
      'Shooting',
      'Scuba Diving',
      'Surfing',
      'Swimming',
      'Taekwondo',
      'Tennis',
      'Volleyball',
      'Skiing'
    ]
  },
  {
    'image': 'assets/images/food.jpg',
    'words': [
      'Salad',
      'Sandwich',
      'Bread',
      'Steak',
      'Tuna Steak',
      'Fish',
      'Shrimp',
      'Rice',
      'Noodles',
      'Spaghetti',
      'Hamburger',
      'Pizza',
      'Eggs',
      'Cheese',
      'Sausages',
      'Apple juice',
      'Grape juice',
      'Beef',
      'Milk',
      'Candy',
      'Cookie',
      'Pie',
      'Cake',
      'Cupcake',
      'Turkey',
      'French fries',
      'Nugget',
      'Bacon',
      'Onion rings',
      'Taco'
    ]
  },
  {
    'image': 'assets/images/country.jpg', //country
    'words': [
      'Australia',
      'Austria',
      'Brazil',
      'Bangladesh',
      'Canada',
      'Cambodia',
      'China',
      'Colombia',
      'Denmark',
      'Egypt',
      'Finland',
      'France',
      'Greece',
      'Hungary',
      'India',
      'Japan',
      'Malaysia',
      'Maldives',
      'Mexico',
      'New Zealand',
      'Netherlands',
      'Norway'
    ]
  },
  {
    'image': 'assets/images/color.png', //color
    'words': [
      'Red',
      'Green',
      'Blue',
      'Pink',
      'Yellow',
      'Orange',
      'Brown',
      'Black',
      'White',
      'Gray',
      'Purple',
      'IndianRed',
      'LightCoral',
      'HotPink',
      'DeepPink',
      'Coral',
      'DarkOrange',
      'Gold',
      'DarkKhaki',
      'Lavender',
      'Violet',
      'BlueViolet',
      'Indigo',
      'Lime',
      'DarkGreen',
      'DarkCyan',
      'SteelBlue',
      'DeepSkyBlue',
      'DarkBlue',
      'Chocolate'
    ]
  },
];
